[package]
name = "mcp-rust-docs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
crates_io_api = { version = "0.11.0", features = ["rustls"] }
regex = "1.11.1"
reqwest = "0.12.23"
rmcp = { version = "0.5.0", features = ["transport-io"] }
schemars = "1.0.4"
scraper = "0.24.0"
serde = "1.0.219"
serde_json = "1.0.143"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
