name: Publish npm package

on:
  workflow_dispatch:

jobs:
  test:
    name: Publish npm package
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache just
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: just

      - name: Cache cargo-license
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: cargo-license

      - name: Cache cargo-about
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: cargo-about

      - name: Install just
        run: |
          if ! command -v just &> /dev/null; then
            cargo install just
          fi

      - name: Build
        run: just build

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Pack
        run: npm pack
